server {
    listen 80;
    server_name fpcn.lspeedl.com;

    # Redirect all HTTP traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name fpcn.lspeedl.com;

    # Let's Encrypt SSL Certificates
    ssl_certificate /etc/letsencrypt/live/lspeedl.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lspeedl.com/privkey.pem;
    
    # SSL settings (improve security)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    # Automatic renewal location for Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location /lib/ {
    root /var/www/html;
    expires 30d;
    add_header Cache-Control "public, no-transform";
    access_log off;
    
    # Add CORS headers
    add_header 'Access-Control-Allow-Origin' '*' always;
    
    # Add CSP headers that allow script execution
    add_header Content-Security-Policy "script-src * 'unsafe-inline' 'unsafe-eval'; connect-src *;" always;
    
    # Optional: Add other security headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    }

    location ~ ^/v1/finger/collect/([^/]+)$ {
        client_max_body_size 50M;
        client_body_timeout 60s;          # Timeout for reading client request body
        client_body_buffer_size 128k;     # Buffer size for reading client request body
        proxy_pass http://localhost:8090;  # Based on your Dockerfile EXPOSE port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;

        # CORS headers for all origins
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type' always;

        # Handle preflight requests
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Content-Type' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

}